import { IInfluenceResult } from './influence-lines.interface';
import { IBeam } from '@/subjects/mechanics-of-solids/cores/sfd-bmd/types';
import { solveReactions } from '@/subjects/mechanics-of-solids/cores/sfd-bmd/reactionSolver';

/**
 * Core engine for calculating the Influence Line Diagram (ILD) of Bending Moment at a specific section.
 * Uses the General Equilibrium Method for compound systems.
 */
export class ILDMomentEngine {
    /**
     * Calculates the exact coordinates for the Bending Moment ILD at section x_c.
     * @param beam The full IBeam structural definition
     * @param targetSectionX The x-coordinate of the cut section (x_c)
     * @returns IInfluenceResult strictly rounded to 3 decimal places
     */
    static calculate(
        beam: IBeam,
        targetSectionX: number
    ): IInfluenceResult {
        // To draw a precise ILD, we evaluate the geometric break points:
        // ends of the beam, support locations, internal releases, and the target section cut.
        const rawPoints = new Set([
            0,
            beam.length,
            ...beam.supports.map((s) => s.position),
            ...beam.releases.map((r) => r.position),
            targetSectionX
        ]);
        const criticalPoints = Array.from(rawPoints).sort((a, b) => a - b);

        const result: IInfluenceResult = [];

        // Identify which supports are structurally to the left of our section cut
        const leftSupports = beam.supports.filter((s) => s.position <= targetSectionX);

        criticalPoints.forEach((x) => {
            const tempBeam: IBeam = {
                ...beam,
                loads: [
                    {
                        id: 'unit-load',
                        type: 'point',
                        magnitude: 1,
                        position: x
                    }
                ]
            };

            const solverRes = solveReactions(tempBeam);

            const getSumLeftReactionMoments = () => {
                if (!solverRes.success) return 0;
                return leftSupports.reduce((sum, s) => {
                    const rxn = solverRes.reactions.find(
                        (r) => r.supportId === s.id && r.type === 'R_y'
                    );
                    const rxnVal = rxn ? rxn.value : 0;
                    const leverArm = targetSectionX - s.position;

                    const rxnMoment = solverRes.reactions.find(
                        (r) => r.supportId === s.id && r.type === 'M'
                    );
                    const momentVal = rxnMoment ? rxnMoment.value : 0;

                    return sum + (rxnVal * leverArm) + momentVal;
                }, 0);
            };

            // 2. Calculate the moment generated by the moving unit load itself
            // If the load is to the left of the cut, it pushes down (-1) generating a negative moment.
            const unitLoadMoment = x < targetSectionX ? -1 * (targetSectionX - x) : 0;

            // 3. Equilibrium: Internal Moment (M_c) balances the FBD
            const momentOrdinate = getSumLeftReactionMoments() + unitLoadMoment;

            result.push({
                x: this.round3(x),
                ordinate: this.round3(momentOrdinate)
            });
        });

        return result;
    }

    /**
     * Generates the step-by-step LaTeX formula strings for the UI Breakdown Panel.
     * @param targetSectionX The x-coordinate of the cut section
     * @param supports Array of all support x-coordinates
     * @returns Array of LaTeX formatted strings explaining the piecewise math
     */
    static getCalculationSteps(targetSectionX: number, supports: number[]): string[] {
        if (supports.length === 2) {
            const sortedSupports = [...supports].sort((a, b) => a - b);
            const supp1 = sortedSupports[0]!;
            const supp2 = sortedSupports[1]!;
            const span = Math.abs(supp2 - supp1);
            const leftSupports = supports.filter(s => s <= targetSectionX);
            const isBetweenSupports = targetSectionX > supp1 && targetSectionX < supp2;

            const steps: string[] = [
                `1. Cut the beam at section $x_c = ${targetSectionX}\\text{ m}$. Use the Equilibrium Method.`
            ];

            if (leftSupports.length > 0) {
                const reactionMoments = leftSupports
                    .map(s => `(R_{${s}} \\times ${this.round3(targetSectionX - s)})`)
                    .join(' + ');

                steps.push(`2. Using the left Free Body Diagram (FBD), sum moments about the cut: $\\sum M_{x_c,\\text{left}} = 0$`);
                steps.push(`$$M_c = ${reactionMoments} - 1 \\times (x_c - x) \\quad \\text{(if load is left of cut)}$$`);
            } else {
                steps.push(`2. The cut is on the left overhang. Using the left FBD (free end):`);
                steps.push(`$$M_c = -1 \\times (${targetSectionX} - x) \\quad \\text{(only when load is left of } x_c)$$`);
            }

            if (isBetweenSupports) {
                const a = targetSectionX - supp1;
                const b = supp2 - targetSectionX;
                const maxOrdinate = (a * b) / span;
                steps.push(`3. Standard peak ordinate formula for mid-span moments: $M_{max} = \\frac{a \\cdot b}{L}$`);
                steps.push(`$$M_{max} = \\frac{${this.round3(a)} \\times ${this.round3(b)}}{${this.round3(span)}} = ${this.round3(maxOrdinate)}\\text{ kN}\\cdot\\text{m}$$`);
            }

            return steps;
        }

        return [
            `1. Cut the beam at section $x_c = ${targetSectionX}\\text{ m}$.`,
            `2. Solve the support reactions for a unit load at position $x$.`,
            `3. Sum the moments of forces to the left of the cut about the cut section:`,
            `$$M_c = \\sum R_{y,\\text{left}}(x_c - x_s) - \\delta(x_c - x)\\quad \\text{where } \\delta = 1 \\text{ if } x < x_c \\text{ else } 0$$`
        ];
    }

    private static round3(val: number): number {
        const rounded = Math.round(val * 1000) / 1000;
        return Math.abs(rounded) < 0.005 ? 0 : rounded;
    }
}
export default ILDMomentEngine;