/**
 * Core interfaces for the Influence Line Diagram (ILD) and Moving Load engines.
 * Conforms to Rule 003: All lengths must be in base SI units (meters) and forces in kN/N.
 */

/**
 * Represents a single calculated data point on an Influence Line Diagram.
 */
export interface IInfluenceOrdinate {
    /** * Position of the moving unit load along the beam (x-axis) in meters.
     */
    x: number;
    /** * The calculated influence value. 
     * Unitless for Support Reactions and Shear force. 
     * Length units (meters) for Bending Moment.
     */
    ordinate: number;
}

/**
 * Represents the complete geometric shape of an Influence Line Diagram,
 * generated by the static or kinematic (Müller-Breslau) engines.
 */
export type IInfluenceResult = IInfluenceOrdinate[];

/**
 * Represents the specific cross-section of the beam being analyzed for Shear or Moment.
 * Denoted as x_c in structural analysis terminology.
 */
export interface ITargetSection {
    /** * The exact position of the section cut from the left end (x=0) of the beam (meters).
     */
    xc: number;
    /** * Optional display label for the section (e.g., 'C' or 'Target').
     */
    label?: string;
}

/**
 * Represents a single axle load within a moving vehicle or train.
 */
export interface IAxleLoad {
    /** * Unique identifier for the axle (e.g., "Front", "Middle", "Rear").
     */
    id: string;
    /** * Magnitude of the point load applied by this specific axle (e.g., kN).
     */
    load: number;
    /** * Distance from the directly preceding axle (meters). 
     * Always 0 for the leading (first) axle in the array.
     */
    spacingFromPrevious: number;
}

/**
 * Represents a moving vehicle (load train) used in absolute maximum convolution analysis.
 * Examples: standard AASHTO HS20-44 highway trucks, custom train bogeys.
 */
export interface IMovingVehicle {
    /** * Human-readable identifier for UI labels (e.g., "HS20-44 Standard Truck").
     */
    name: string;
    /** * Array of axles ordered from front to back. 
     * The convolution engine will step this array across the beam span.
     */
    axles: IAxleLoad[];
}

/**
 * Defines the contract for the absolute maximum analyzer response.
 */
export interface IMovingLoadMaxResult {
    /** The maximum absolute value calculated during the entire transit */
    absoluteMax: number;
    /** The specific position of the leading axle (x) that produced the maximum value */
    criticalLeadingAxlePosition: number;
    /** The mathematical breakdown strings for UI display */
    calculationSteps: string[];
}

/**
 * Represents an individual added target diagram in the list of influence lines.
 */
export interface IInfluenceTarget {
    id: string;
    type: 'reaction' | 'shear' | 'moment';
    targetSupportX: number | null;
    targetSection: ITargetSection;
    isVisible: boolean;
}